name: Build and Deploy API Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bundle and Build API Docs
        run: ./make.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: .
          force_orphan: true
          exclude_assets: '.github,openapi,redocly.yaml,make.sh'