name: Build and Deploy API Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest
      - name: Bundle Docs
        run: redocly bundle -o brewery-oa3.yaml
      - name: Build API Docs
        run: redocly build-docs brewery-oa3.yaml -o index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: .
          force_orphan: true
          exclude_assets: '.github,openapi,redocly.yaml,make.sh'